services:
  db:
    image: postgres:16
    container_name: medtrack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: medtrack
      POSTGRES_PASSWORD: medtrack_dev_password
      POSTGRES_DB: medtrack
    ports:
      - "5432:5432"
    volumes:
      - medtrack_pgdata:/var/lib/postgresql/data

  app:
    build: 
      context: .
      args:
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: "BOGYdxFB5DiTbPsfF6afvqcShZEV2avmhHFaKqd9EpNcTd9twHFhzsJmgd2YzSnAV_6vae2tX5mkdfZ58yUpxD4"
    container_name: medtrack-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://medtrack:medtrack_dev_password@db:5432/medtrack?schema=public"
      VAPID_PUBLIC_KEY: BOGYdxFB5DiTbPsfF6afvqcShZEV2avmhHFaKqd9EpNcTd9twHFhzsJmgd2YzSnAV_6vae2tX5mkdfZ58yUpxD4
      VAPID_PRIVATE_KEY: YGMctyjztiSsxwGdibre_l_g4WNOb-rOLTuxmF-8YO8
      VAPID_SUBJECT: "mailto:cbiskit31@gmail.com"
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: BOGYdxFB5DiTbPsfF6afvqcShZEV2avmhHFaKqd9EpNcTd9twHFhzsJmgd2YzSnAV_6vae2tX5mkdfZ58yUpxD4
    ports:
      - "3001:3000"

volumes:
  medtrack_pgdata:
    external: true
